Update governance README.md
LBRYFoundation/lbry.org pull request #204
Opened 2024-08-04 23:58 UTC by AQ00111111

Brief update.

2024-08-05 07:28 UTC, ben221199 requested changes

2024-08-05 07:28 UTC, ben221199 commented on docs/governance/README.md
> +  name="Ben 'Ben'"
Change to:
```html
  name="Ben 'ben221199'"
```

2024-08-05 14:31 UTC, Pigges approved these changes

2024-08-06 18:26 UTC, Pigges approved these changes

2024-08-06 18:28 UTC, merged